// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"ha8uxq24cl","name":"permissionsCRUD","description":"","endpoint":"https://ha8uxq24cl.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/permissions","/permissions/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:b0f50318-c5d6-4b1c-a2a5-3df5125e73d6',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'seed-hosting-mobilehub-105633263',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dq2s9sdt9efje.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"seed-mobilehub-105633263-permissions","attributes":[{"name":"userId","type":"S"},{"name":"clearance","type":"N"},{"name":"keys","type":"SS"}],"indexes":[],"region":"us-east-1","hashKey":"userId"}],
    'aws_mobile_analytics_app_id': 'f983065947834173a9bea36ceb652a5d',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '08759723-2185-4ce1-9216-f59054e859d3',
    'aws_project_name': 'seed',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'seed-deployments-mobilehub-105633263',
    'aws_resource_name_prefix': 'seed-mobilehub-105633263',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_MIawOvbZK',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '1vpqf631m1pe548vhur4k516d1',
}

export default awsmobile;
