// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:95ea9a79-bd2b-4509-9b5d-9bc73a6d206e',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'freelaneseed-hosting-mobilehub-1585871626',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3grdapob1crvd.cloudfront.net',
    'aws_mobile_analytics_app_id': 'c6f045a1bea14d03bce36a05a52b3fb9',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'dc38ed9a-85fb-4375-8d88-2820e524cb3e',
    'aws_project_name': 'freelane_seed',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'freelaneseed-mobilehub-1585871626',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_zKcYrkMNx',
    'aws_user_pools_web_client_id': '5ocmg5b84qa5di1p7ioeit40o3',
}

export default awsmobile;
